/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/Activity.vue')['default']
    AircraftTypeSelect: typeof import('./src/components/selector/AircraftTypeSelect.vue')['default']
    AirlineSelect: typeof import('./src/components/selector/AirlineSelect.vue')['default']
    AirportSelect: typeof import('./src/components/selector/AirportSelect.vue')['default']
    ContactPanel: typeof import('./src/components/ContactPanel.vue')['default']
    CreateAirline: typeof import('./src/components/CreateAirline.vue')['default']
    CreateAirport: typeof import('./src/components/CreateAirport.vue')['default']
    CreateAirtype: typeof import('./src/components/CreateAirtype.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImgLoader: typeof import('./src/components/ImgLoader.vue')['default']
    InfoLabel: typeof import('./src/components/InfoLabel.vue')['default']
    PhotoTypeSelect: typeof import('./src/components/PhotoTypeSelect.vue')['default']
    RejectThumbnail: typeof import('./src/components/RejectThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumbnail: typeof import('./src/components/Thumbnail.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
