/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/HeadPhoto copy 2.vue')['default']
    Activity: typeof import('./src/components/Activity.vue')['default']
    AircraftTypeSelect: typeof import('./src/components/selector/AircraftTypeSelect.vue')['default']
    AirlineSelect: typeof import('./src/components/selector/AirlineSelect.vue')['default']
    AirportSelect: typeof import('./src/components/selector/AirportSelect.vue')['default']
    Carousel: typeof import('./src/components/photo/Carousel.vue')['default']
    copy: typeof import('./src/components/HeadPhoto copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FirstScreen: typeof import('./src/components/firstScreen/FirstScreen.vue')['default']
    FirstScreenMobile: typeof import('./src/components/firstScreen/FirstScreenMobile.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeadBar: typeof import('./src/components/header/HeadBar.vue')['default']
    HeadBar1: typeof import('./src/components/HeadBar-1.vue')['default']
    HeadPhoto: typeof import('./src/components/HeadPhoto.vue')['default']
    'HeadPhoto copy': typeof import('./src/components/HeadPhoto copy.vue')['default']
    'HeadPhoto copy 2': typeof import('./src/components/HeadPhoto copy 2.vue')['default']
    LoginButton: typeof import('./src/components/header/LoginButton.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NewPhotos: typeof import('./src/components/NewPhotos.vue')['default']
    PhotoBox: typeof import('./src/components/photo/PhotoBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/header/SearchBox.vue')['default']
    StatisticInfoBox: typeof import('./src/components/StatisticInfoBox.vue')['default']
    Thumbnail: typeof import('./src/components/Thumbnail.vue')['default']
    TransparentButton: typeof import('./src/components/TransparentButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
